coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 0%
    patch:
      default:
        target: 95%
        threshold: 0%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
