
name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
  schedule:
    # Run weekly
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 0'

defaults:
  run:
    shell: bash -leu {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11', '3.12', '3.13', '3.14', '3.14t']
        include:
          - os: ubuntu-22.04
            python-version: '3.10'
      fail-fast: false

    steps:
    - uses: actions/checkout@v6
    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@93556350e3433849ea434d68e8b8f7d9e9a402a4 # v1
    - name: Install uv
      uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4
    - name: Setup octave
      uses: ./
      with:
        install-type: ubuntu
    - name: Install just
      uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3
    - name: Install dependencies
      run: |
        just install
        just docker-build
    - name: Run test on linux
      run: |
         uv run python -m octave_kernel.check
         just cover
         just test-kernel
         just test-notebook
         uv run python -m octave_kernel install --user

  test-other-systems:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            install-type: macos
          - os: windows-latest
            install-type: windows
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@93556350e3433849ea434d68e8b8f7d9e9a402a4 # v1
    - name: Install uv
      uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4
    - name: Install just
      uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6 # v2
    - name: Setup octave
      uses: ./
      with:
        install-type: ${{ matrix.install-type }}
    - name: Run tests
      run: |
        just test
        just test-kernel

  test-other-ubuntu:
    strategy:
      matrix:
        install-type: [ubuntu-flatpak, ubuntu-snap]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@93556350e3433849ea434d68e8b8f7d9e9a402a4 # v1
    - name: Install uv
      uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4
    - name: Install just
      uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6 # v2
    - name: Setup octave
      uses: ./
      with:
        install-type: ${{ matrix.install-type }}
    - name: Install dependencies
      run: just install
    - name: Run tests
      run: |
        just test
        just test-kernel
    - name: Test notebook
      if: ${{ matrix.install-type != 'ubuntu-flatpak' }}
      run: just test-notebook

  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@93556350e3433849ea434d68e8b8f7d9e9a402a4 # v1
      - uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3
      - uses: jupyterlab/maintainer-tools/.github/actions/make-sdist@93556350e3433849ea434d68e8b8f7d9e9a402a4 # v1

  test_sdist:
    runs-on: ubuntu-latest
    needs: [make_sdist]
    name: Install from SDist and Test
    timeout-minutes: 20
    steps:
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@93556350e3433849ea434d68e8b8f7d9e9a402a4 # v1
      - uses: jupyterlab/maintainer-tools/.github/actions/test-sdist@93556350e3433849ea434d68e8b8f7d9e9a402a4 # v1
        with:
          test_command: "jupyter kernelspec list | grep octave"

  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@93556350e3433849ea434d68e8b8f7d9e9a402a4 # v1
      - name: Install uv
        uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4
      - name: Install just
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3
      - name: Run pre-commit
        run: just pre-commit
      - name: Run typing check
        run: just typing

  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@93556350e3433849ea434d68e8b8f7d9e9a402a4 # v1
      - name: Install uv
        uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4
      - name: Check Release
        uses: jupyter-server/jupyter_releaser/.github/actions/check-release@3e74486d1011d24cd5e9977202fd349dece0db9c # v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  link_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@93556350e3433849ea434d68e8b8f7d9e9a402a4 # v1
      - uses: jupyterlab/maintainer-tools/.github/actions/check-links@93556350e3433849ea434d68e8b8f7d9e9a402a4 # v1
        with:
          ignore_links: "http://nbviewer.ipython.org/*"

  tests_check: # This job does nothing and is only used for the branch protection
    if: always()
    needs:
      - test-linux
      - test-other-systems
      - test-other-ubuntu
      - make_sdist
      - test_sdist
      - static
      - check_release
      - link_check
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # release/v1
        with:
          jobs: ${{ toJSON(needs) }}
